### PR TITLE
PR for issue/21

### PR DESCRIPTION
**Pull request by NicolasRouquette**
- Added a third argument to Post() for processing the response contents before the connection is closed
- Added sonatypeOpen & createStage

### CODE REVIEW

**Comment by xerial** [comment]
Hi @NicolasRouquette,

Thanks for the PR. And the change looks good as long as it's backward compatible. Could you add a usage note to README.md with an example of workflow that uses these new command?

**Comment by NicolasRouquette** [comment]
Ok, I'm testing an example workflow.

**Comment by NicolasRouquette** [comment]
@xerial per your request, I added a file, [workflow.md](https://github.com/xerial/sbt-sonatype/pull/22/files#diff-7b3ce5b849b571e162bc8896a9240e7b), that shows a workflow using the sonatype commands (Open, Close, ...).

**Comment by NicolasRouquette** [comment]
@xerial I'm done with the updates for this PR.

**Comment by xerial** [comment]
Merged and released as 1.1. Thanks!

**Pull request merged**
